version: 0.2
phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y unzip
      - curl -O https://releases.hashicorp.com/terraform/1.1.5/terraform_1.1.5_linux_amd64.zip
      - unzip terraform_1.1.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - terraform --version
      - terraform init
      - terraform plan
      - terraform fmt
      - terraform validate
  build:
    commands:
      - cd project
      - terraform apply --auto-approve
  post_build:
    commands:
      - terraform state list
